//DIGITAL INPUTS
#define TEST_STOP_BUTTON 0 // FOR TESTING

//ANALOG INPUTS
#define TAPE_FOLLOWING_QRD_RIGHT  0
#define TAPE_FOLLOWING_QRD_LEFT 2
#define INTERSECTION_QRD_RIGHT 4
#define INTERSECTION_QRD_LEFT 6

//MOTOR OUTPUTS
#define MOTOR_RIGHT_WHEEL 0
#define MOTOR_LEFT_WHEEL 3

// QRD to ground threshold
#define QRD_GROUND_THRESHOLD 200

enum direction_e {
  LEFT,RIGHT,FORWARD
};

